# Exception

简介 : Java语言中,将`程序执行中发生的不正常情况称为"异常"`,(开发过程中的语法错误和逻辑错误不是异常);

*异常可以分为两类* :

1. Error(`严重错误,程序会崩溃`): JVM 无法解决的严重问题  --> 系统内部错误,资源耗尽等严重情况; 
2. Exception: 程序不会崩溃,可以使用针对性的代码进行处理;
     - Exception分两大类:
       - 运行时异常: 程序运行时,发生的异常  (运行异常普遍,可不作处理 --> 存在默认处理机制`throws Exception JVM`)
       - 编译时异常: 编程时,编译器检查出的异常(编译器要求必须处置的异常)

# Exception System Diagram

![image-20230422142522984](https://banne.oss-cn-shanghai.aliyuncs.com/Java/image-20230422142522984.png)

# Runtime Exception

- **NullPointerException**

  - 空指针异常

  - ```java
             String name = null;
            // 抛出NullPointerException
            System.out.println(name.length()); 
    ```

- **ArithmeticException**

  - 算术异常

  - ```java
           int num1 = 10;
           int num2 = 0;
           //抛出算数运算异常
           int res = num1 / num2;
    ```

- **ArrayIndexOutOfBoundsException**

  - 数组下标越界异常

  - ```java
       int[] arr =new int[5];
    //抛出数组下标越界异常
       System.out.println(arr[5]);
    ```

- **ClassCastException**

  - 类转换异常

  - ```java
    public class ClassCastException_ {
        public static void main(String[] args) {
            A a = new B(); //向上转型
            B b2 = (B)a;   //向下转型，这里是 OK
            C c2 = (C)a;//向下转型出现异常
        }
    }
    class A {}
    class B extends A {}
    class C extends A {}
    ```

- **NumberFormatException**

  - 数值转换格式异常

  - ```java
            String name ="小编";
    //数值转格式错误  发出异常
    System.out.println(Integer.parseInt(name));
    ```

# Compile Exception

- **SQLException  SQL 操作异常**

- **IOException  IO 文件异常**

- **ClassNotFoundException  类找不到异常**

- **FileNotFoundException  文件找不到异常**

  - ```java
    FileInputStream fis  =  new  FileInputStream("/test.txt"); 
    ```

- **EOFException 文件操作异常**
- **IllegalArgumentException 参数异常**

# Exception Handling

简介 : 异常发生时,对异常的处理方式;

*异常处理的方式 :*

1. try-catch-finally  捕获发生的异常,自行处理;

2. throws 将发生的异常抛出,交给方法的调用者来处理(`最顶级的处理者是JVM`)

## Try-Catch-Finally

*try-catch-finally 处理机制 :*

try 包裹可能出现异常的代码    `try-catch快捷键 alt + ctrl +t`

catch 捕获异常, 处理异常  -->  发生异常时,系统将异常封装成Exception类 对象e传递给catch,得到对象e后自行处理;

finally 最终处理, 不管有没有捕获异常, 都会`必须`执行 finally 

如果发生异常, try 中的其他代码就不会执行了, 直接进入 catch 处理异常

如果没有发生异常, 就不会进入 catch

如果没有finally ,语法正常通过 

```java
public class TryCatch {
    public static void main(String[] args) {
        /*try代码块出现多个异常:
        1.使用多个catch 分别捕获不同的异常,相应处理
        2.子类异常在前,父类异常出现在最后
        */
        try {
            Person person = new Person();
            person = null;
            System.out.println(person.name); // NullPointerException
            int [] arr = new int[10];
            System.out.println(arr[10]); // ArrayIndexOutOfBoundsException
        }catch(NullPointerException e){  //对应不同的子类异常
            System.out.println("空指针异常: "+e.getMessage());
        } catch (Exception e) {   //父类异常
            System.out.println("数组下标越界异常: "+e.getMessage());
        }finally {
            System.out.println("执行finally代码");
        }
    }
}
class Person{
    String name;
}
```

无论try中代码是否异常,都会执行finally中的业务逻辑,若出现异常执行完finally代码程序崩溃,如下 :

```java
   try{
            System.out.println(10/0);  //出现 ArithmeticException
        }finally{
            System.out.println("finally代码被执行 ! ! "); //没有catch,try出现异常直接 执行finally代码可输出(finally代码被执行),然后程序崩溃
        }
        System.out.println("程序继续执行 ! ! ! ");//无法执行 
```

## Throws

*throws 处理机制 :*

如果不确定如何处理异常, 可以通过 throws 抛出异常, 交给方法的调用者来处理

方法的调用者也可以抛出异常, JVM 是最顶级的的方法处理者, 直接输出异常信息

如果程序即没有 try catch finally, 也没有 throws, (运行类型异常)则方法默认有一个 throws () 

 <img src="https://banne.oss-cn-shanghai.aliyuncs.com/Java/image-20230422154331778.png" alt="image-20230422154331778" style="zoom: 67%;" />

```java
public class ExceptionThrows {
    public static void main(String[] args) {
        // 调用 Say() 方法 --> 处理异常
        try {
            Say();
        } catch (ArithmeticException e) {
            System.out.println("算数运算异常"); // 算数运算异常
        }
    }
    static void Say() throws ArithmeticException{
        // 存在运行异常  --> 通过throws进行抛出,交给该方法的调用者处理
        System.out.println(10 / 0);
    }
}
```

子类重写父类方法时,所抛出的异常类型要么和父类抛出异常一致;要么是父类抛出异常类型的子类;如下 :

```java
class Animal{
    //f1() 抛出的异常为 RuntimeException
    void f1()throws RuntimeException{};
    //f2() 抛出的异常为 Exception
    void f2()throws Exception{};
}

class Dog extends Animal{
    //子类重写父类的f1()方法 抛出的异常和父类相同;
    @Override
    void f1() throws RuntimeException {}
    // 子列重写父类f2()方法 抛出异常是父类抛出异常类型的子类型
    @Override
    void f2() throws FileNotFoundException {}
}
```

*Throws 和 Throw的区别 :*

![image-20230422204851707](https://banne.oss-cn-shanghai.aliyuncs.com/Java/image-20230422204851707.png)

# Custom Exception

```java
public class CustomException {
    public static void main(String[] args) {
        int age = 180;
        // 年龄在 18 -120 之间 否则抛出异常
        if(!(age >= 18 && age <= 120)){
            // 抛出异常 --> 通过构造器,设计信息
            throw new AgeException("年龄在 18 -120 之间");
        }
        System.out.println("年龄范围正确");
    }
}
// 自定义异常 推荐  运行类型异常 RuntimeException,可以使用默认的异常处理机制
class AgeException extends RuntimeException{
    // 构造器
    public AgeException(String message) {
        super(message);
    }
}
// 编译类型异常  继承 Exception
class FileException extends Exception{
    public FileException(String message) {
        super(message);
    }
}
```

 
